namespace: lotto
resources:
- namespace-lotto.yaml
- deployment-lotto-service.yaml
- deployment-random-number-service.yaml
- deployment-web.yaml
- ingress-web.yaml
- service-lotto-service.yaml
- service-random-number-service.yaml
- service-web.yaml
