# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
name: lotto-microservices
services:
- name: randomnumberservice
  image: dlindemann/randomnumberservice:0.0.1
  dockerFile: ./Dockerfile
  project: /workspaces/lotto-microservices/src/RandomNumberService/RandomNumberService.csproj
  bindings:
  - port: 8081
    containerPort: 5000
    protocol: http
  env:
  - name: ASPNETCORE_URLS
    value: http://+:5000
- name: lottoservice
  image: dlindemann/lottoservice:0.0.1
  dockerFile: ./Dockerfile
  project: /workspaces/lotto-microservices/src/LottoService/LottoService.csproj
  bindings:
  - port: 8082
    containerPort: 5000
    protocol: http
  env:
  - name: ASPNETCORE_URLS
    value: http://+:5000
  - name: RandomNumberService__Url
    value: http://randomnumberservice:5000
- name: web
  image: dlindemann/lottoweb:0.0.1
  dockerFile: ./Dockerfile
  project: /workspaces/lotto-microservices/src/Web/Web.csproj
  bindings:
  - port: 8083
    containerPort: 5000
    protocol: http
  env:
  - name: ASPNETCORE_URLS
    value: http://+:5000
  - name: LottoService__Url
    value: http://localhost:8082
