version: '3.8'

services:
  lottoservice:
    image: dlindemann/lottoservice:0.0.1
    build:
      context: ./src/LottoService
      dockerfile: ./Dockerfile
    ports:
      - "8082:5000"
    environment:
      - RandomNumberService__Url=http://randomnumberservice:5000
  randomnumberservice:
    image: dlindemann/randomnumberservice:0.0.1
    build:
      context: ./src/RandomNumberService
      dockerfile: ./Dockerfile
    ports:
      - "8081:5000"
  web:
    image: dlindemann/lottoweb:0.0.1
    build:
      context: ./src/Web
      dockerfile: ./Dockerfile
    ports:
      - "8080:5000"
    environment:
      - Api=http://lottoservice:5000
  redis:
    image: redis
    ports:
      - "6379:6379"
  seq:
    image: datalust/seq
    ports:
      - "5341:5341"
      - "8181:80"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=FOoLKaSS397/a51nyq1E6SLYqNFiahTpRN8+dem1EpRA60X2KQ== # password
    volumes:
      - ./.docker-data/seq:/data
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
