services:
  randomnumberservice:
    image: dlindemann/randomnumberservice:0.0.1
    build:
      context: ./src/RandomNumberService
      dockerfile: ./Dockerfile
    ports:
      - "8081:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
  lottoservice:
    image: dlindemann/lottoservice:0.0.1
    build:
      context: ./src/LottoService
      dockerfile: ./Dockerfile
    ports:
      - "8082:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - RandomNumberService__Url=http://randomnumberservice:5000
  web:
    image: dlindemann/lottoweb:0.0.1
    build:
      context: ./src/Web
      dockerfile: ./Dockerfile
    ports:
      - "8083:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - LottoService__Url=http://localhost:8082 # this get called by the spa client
