# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
name: lotto-microservices
services:
- name: web
  project: src/Web/Web.csproj
  env:
    - name: ASPNETCORE_HOSTINGSTARTUPASSEMBLIES
      value: Microsoft.AspNetCore.SpaProxy
- name: randomnumberservice
  project: src/RandomNumberService/RandomNumberService.csproj
- name: lottoservice
  project: src/LottoService/LottoService.csproj
- name: redis
  image: redis
  bindings:
  - port: 6379
    connectionString: "127.0.0.1:${port}" 
- name: redis-cli
  image: redis
  args: "redis-cli -h redis MONITOR"
