apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: random-number-service
  name: random-number-service
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: randomnumberservice
        env:
        - name: APPINSIGHTS_INSTRUMENTATIONKEY
          valueFrom:
            configMapKeyRef:
              key: instrumentation_key
              name: appinsights
