apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lotto-service
  name: lotto-service
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: lottoservice
        env:
        - name: APPINSIGHTS_INSTRUMENTATIONKEY
          valueFrom:
            configMapKeyRef:
              key: instrumentation_key
              name: appinsights
            