FROM mcr.microsoft.com/dotnet/sdk:5.0-alpine AS publish
WORKDIR /src
COPY ["LottoService.csproj", "./"]
RUN dotnet restore "LottoService.csproj" --runtime alpine-x64
COPY . .

# optimize dotnet publish
RUN dotnet publish "LottoService.csproj" -c Release -o /app/publish \
    --no-restore \
    --runtime alpine-x64 \
    --self-contained true \
    /p:PublishTrimmed=true \
    /p:PublishSingleFile=true

FROM mcr.microsoft.com/dotnet/runtime-deps:5.0-alpine AS final

# create a new user and change directory ownership
RUN adduser --disabled-password \
  --home /app \
  --gecos '' appuser && chown -R appuser /app

# impersonate into the new user
USER appuser
WORKDIR /app

EXPOSE 5000
COPY --from=publish /app/publish .

ENTRYPOINT ["./LottoService", "--urls", "http://0.0.0.0:5000"]

