apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  template:
    spec:
      containers:
      - name: lottoweb
        envFrom:
        - configMapRef:
            name: configmap-web
        env:
        - name: LottoService__Url
          value: http://lotto-service:8080
          $patch: delete
