apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-web
  labels:
    app: web
spec:
  ingressClassName: nginx
  rules:
    - host: web.lotto.dlindemann.xyz
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: web
                port:
                  number: 8080
  # # This section is only required if TLS is to be enabled for the Ingress
  # tls:
  #   - hosts:
  #     - www.example.com
  #     secretName: example-tls