apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-lotto-service
  labels:
    app: lotto-service
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: api.lotto.dlindemann.xyz
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: lotto-service
                port:
                  number: 8080
