resources:
- ../../base

images:
- name: dlindemann/lottoservice
  newName: crdlibasta2022.azurecr.io/dlindemann/lottoservice
  newTag: 1.0.0
- name: dlindemann/randomnumberservice
  newName: crdlibasta2022.azurecr.io/dlindemann/lottoservice
  newTag: 1.0.0
- name: dlindemann/lottoweb
  newName: crdlibasta2022.azurecr.io/dlindemann/lottoservice
  newTag: 1.0.0
