resources:
- ../../base
# - ingress-web.yaml
# - ingress-lotto-service.yaml

commonLabels:
  environment: prod
  hosted-on: azure

# container registry will not be available after basta 2022
# recreate it, if required

images:
- name: dlindemann/lottoservice
  newName: crdlibasta2022.azurecr.io/dlindemann/lottoservice
  newTag: 1.0.0
- name: dlindemann/randomnumberservice
  newName: crdlibasta2022.azurecr.io/dlindemann/randomnumberservice
  newTag: 1.0.0
- name: dlindemann/lottoweb
  newName: crdlibasta2022.azurecr.io/dlindemann/lottoweb
  newTag: 1.0.0
